### PR TITLE
Fix some issues in first-time user experience.

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Comment by jeschu1** [comment]
Please add a picture for this change.

**Comment by jeschu1** [comment]
Can you verify the unit tests pass for you?  I am seeing failures on 
- testLoad_TfDetected
- testLoad_TfCmdSaved
- testLoad_TfNotFound

**Comment by mfilippov** [comment]
@jeschu1 fixed.

**Comment by mfilippov** [comment]
@jeschu1 This PR ready to merge.

**Pull request merged**
